/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import adm.Conexion;
import adm.IngProveedor;
import adm.Limpiar_Caja;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import metodo.Proveedor;
import metodo.Tabla;

/**
 *
 * @author usuario
 */
public class FrameListaPro extends javax.swing.JFrame {
    Tabla t = new Tabla();
    Limpiar_Caja l = new Limpiar_Caja();
    IngProveedor pro;
    int clic_tabla = 0;
    /**
     * Creates new form FrameListaPro
     */
    public FrameListaPro() {
        initComponents();
        t.ver_proveedor(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Listado de Proveedores");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        clic_tabla = this.tabla.rowAtPoint(evt.getPoint());
            String id = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            String cedula = tabla.getValueAt(tabla.getSelectedRow(), 1).toString();
            String nombre = tabla.getValueAt(tabla.getSelectedRow(), 2).toString();
            String apellido = tabla.getValueAt(tabla.getSelectedRow(), 3).toString();
            String direccion = tabla.getValueAt(tabla.getSelectedRow(), 4).toString();
            String telefono = tabla.getValueAt(tabla.getSelectedRow(), 5).toString();
            int column = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
            int row = evt.getY()/tabla.getRowHeight();
            if(row < tabla.getRowCount() && row >= 0 && column < tabla.getColumnCount() && column >= 0){
            Object value = tabla.getValueAt(row, column);
                Conexion c = new Conexion();
                Connection con = c.gettConexion();
                Statement stat;
                if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                Proveedor p = new Proveedor();
                    p.setIdProveedor(Integer.parseInt(id));
                    p.setCedula(cedula);
                    p.setNombre(nombre);
                    p.setApellido(apellido);
                    p.setDireccion(direccion);
                    p.setNumero(Integer.parseInt(telefono));
                if(boton.getName().equals("m")){
                    String sql = "update proveedor set cedula='"+cedula+"', nombre='"+nombre+"',apellido='"+apellido+"',direccion='"+direccion+"',telefono='"+telefono+"' where idProveedor='"+id+"';";
                    try {
                        stat = con.createStatement();
                        stat.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Registro actualizado");
                    } catch (SQLException ex) {
                        Logger.getLogger(FrameListaP.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }else JOptionPane.showMessageDialog(null, "No se puede Actualizar");
                
                if(boton.getName().equals("e")){
                        String query = "delete from proveedor where idProveedor='"+id+"';";
                        try {
                        stat = con.createStatement();
                        stat.executeUpdate(query);
                        JOptionPane.showMessageDialog(null, "Registro eliminado");
                    } catch (SQLException ex) {
                        Logger.getLogger(FrameListaP.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameListaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameListaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameListaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameListaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameListaPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
